version: '2'

networks:
    mb:
        external: true

services:
    php:
        build: docker/php
        working_dir: /var/www/app
        networks:
            mb:
                aliases:
                    - php
            default:
                aliases:
                    - php.mb
        volumes:
            - .:/var/www/app
            - ~/.composer:/var/www/.composer
            - ~/.npm:/var/www/.npm
            - ~/.npmrc:/var/www/.npmrc
#        depends_on:
#            - db

    web:
        image: nginx:1-alpine
        networks:
            mb:
                aliases:
                    - web
            default:
                aliases:
                    - web.mb
        volumes:
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/app
            - ./var/logs/nginx/:/var/log/nginx
        expose:
            - 80
        depends_on:
            - php
#
#    db:
#        image: postgres:9.6
#        ports:
#            - "5433:5432"
#        networks:
#            mb:
#                aliases:
#                    - db
#            default:
#                aliases:
#                    - db.mb
#        volumes:
#            - ./docker/db:/usr/local/src
