version: '2'

networks:
    skeleton:
        external: true

services:
    php:
        image: mbutelle/docker-web-app:0.1
        working_dir: /var/www/app
        networks:
            skeleton:
                aliases:
                    - php
            default:
                aliases:
                    - php.skeleton
        volumes:
            - .:/var/www/app
            - ~/.composer:/var/www/.composer
            - ~/.npm:/var/www/.npm
            - ~/.yarnrc:/var/www/.yarnrc
#        depends_on:
#            - db

    web:
        image: nginx:1-alpine
        networks:
            skeleton:
                aliases:
                    - web
            default:
                aliases:
                    - web.skeleton
        volumes:
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/app
            - ./var/logs/nginx/:/var/log/nginx
        expose:
            - 80
        depends_on:
            - php

#    db:
#        image: mysql
#        command: --default-authentication-plugin=mysql_native_password
#        environment:
#          - MYSQL_ROOT_PASSWORD=root
#        networks:
#            skeleton:
#                aliases:
#                    - db
#            default:
#                aliases:
#                    - db.skeleton
#        volumes:
#            - ./docker/db:/usr/local/src
